services:
    hana-app-pdf:
        image: nicklas373/hana-app-pdf-sit:1.8
        container_name: "hana-app-pdf"
        cpus: 2.0
        mem_limit: 512M
        mem_reservation: 256M
        restart: unless-stopped
        working_dir: /var/www/html/hanaci-pdf
        ports:
            - "81:81"
        environment:
            - APP_NAME=pdf.hana-ci.com
        volumes:
            - hana-app-pdf:/var/www/html/hanaci-pdf
        networks:
            - hana-network
        depends_on:
            - hana-api-services
    hana-api-services:
        image: nicklas373/hana-api-services-sit:2.3
        container_name: "hana-api-services"
        cpus: 2.0
        mem_limit: 512M
        mem_reservation: 256M
        restart: always
        working_dir: /var/www/html/hanaci-api
        ports:
            - "80:80"
        environment:
            - APP_NAME=gw.hana-ci.com
        volumes:
            - hana-api-services:/var/www/html/hanaci-api
        networks:
            - hana-network
        depends_on:
            - hana-db-services
    hana-minio:
        image: pgsty/minio:latest
        container_name: "hanaci-minio"
        cpus: 1.0
        mem_limit: 512M
        mem_reservation: 256M
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9001:9001"
        networks:
            - hana-network
        volumes:
            - minio-data:/data
            - minio-config:/root/.minio
        environment:
        MINIO_ROOT_USER: "eureka"
        MINIO_ROOT_PASSWORD: "eureka"
        command: server /data --console-address ":9001"
    hana-db-services:
        image: postgres:18.3
        container_name: "hana-db-services"
        restart: unless-stopped
        cpus: 1.0
        mem_limit: 256M
        mem_reservation: 128M
        ports:
            - "${DB_PORT:-5432}:5432"
        env_file:
            - .env
        environment:
            PGPASSWORD: "postgres"
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "master"
            POSTGRES_PASSWORD: "postgres"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "hana-db-services:/var/lib/postgresql/data"
            - "./module/instance/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
        networks:
            - hana-network
        depends_on:
            - hana-instance-services
networks:
    hana-network:
        driver: bridge
volumes:
    hana-db-services:
        driver: local
    minio-data:
        driver: local
    minio-config:
        driver: local
