# Use php:8.5-fpm-alpine3.22 as base image
FROM php:8.5-fpm-alpine3.22

# Configure image maintainer
LABEL maintainer="Nicklas373 <herlambangdicky5@gmail.com>"
LABEL version="1.8"
LABEL description="Docker application image for HANA PDF Apps"

# Configure work directory
WORKDIR /var/www/html

# Configure timezone
RUN apk update && \
    apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && \
    echo "Asia/Jakarta" > /etc/timezone

# Configure initial packages
RUN apk add --no-cache \
    curl \
    unzip \
    git \
    libzip-dev \
    libpq-dev \
    postgresql-dev \
    supervisor \
    nginx \
    bash \
    busybox-suid \
    nano

# Install PHP extensions
RUN docker-php-ext-install -j$(nproc) pdo_pgsql

# Clone App Services
RUN git clone -b dev/fe/master-live https://github.com/Nicklas373/Hana-PDF hanaci-pdf

# Configure Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN cd hanaci-pdf && composer install --no-interaction --no-scripts --no-progress --prefer-dist

# Configure App Service
COPY module/php/php.ini /usr/local/etc/php/conf.d/99-hana.ini
RUN cd hanaci-pdf && cp .env.example .env
RUN cd hanaci-pdf && \
    php artisan key:generate && \
    php artisan config:cache && \
    php artisan config:clear

# Configure permission
RUN cd hanaci-pdf && \
    chmod o+w /var/www/html/hanaci-pdf/storage/ -R

# Configure Laravel Env
RUN cd hanaci-pdf && echo "VITE_ADOBE_CLIENT_ID=xxxx" >> .env
RUN cd hanaci-pdf && echo "" >> .env
RUN cd hanaci-pdf && sed -i 's/APP_NAME=Laravel/APP_NAME="HANA PDF"/' .env
RUN cd hanaci-pdf && sed -i "s#APP_URL=http://localhost#APP_URL=http://sit.pdf.hana-ci.com#" .env
RUN cd hanaci-pdf && sed -i "s/DB_CONNECTION=mysql/DB_CONNECTION=pgsql/" .env
RUN cd hanaci-pdf && sed -i "s/DB_HOST=127.0.0.1/DB_HOST=hana-db-services/" .env
RUN cd hanaci-pdf && sed -i "s/DB_PORT=3306/DB_PORT=5432/" .env
RUN cd hanaci-pdf && sed -i "s/DB_DATABASE=laravel/DB_DATABASE=postgres/" .env
RUN cd hanaci-pdf && sed -i "s/DB_USERNAME=root/DB_USERNAME=$DB_USERNAME/" .env
RUN cd hanaci-pdf && sed -i "s/DB_PASSWORD=/DB_PASSWORD=$DB_PASSWORD/" .env
RUN cd hanaci-pdf && echo "TELEGRAM_BOT_ID=xxxx" >> .env
RUN cd hanaci-pdf && echo "TELEGRAM_CHAT_ID=xxxx" >> .env

# Configure nginx instances
RUN mkdir /etc/nginx/sites-enabled
COPY module/nginx/nginx.conf /etc/nginx/nginx.conf
COPY module/nginx/sites-available/pdf-hanaci.conf /etc/nginx/sites-available/pdf-hanaci.conf
RUN ln -s /etc/nginx/sites-available/pdf-hanaci.conf /etc/nginx/sites-enabled/

# Set up cron job for Laravel scheduler
COPY module/hanaci/hanaci-pdf/pdf-cron /etc/crontabs/root
RUN touch /var/log/cron.log && chmod 0644 /var/log/cron.log

# Configure supervisord
COPY module/instance/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Expose necessary ports
EXPOSE 81 9000

# Start Nginx and PHP-FPM with supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
