# Use php:8.4.14-fpm-alpine as base image
FROM php:8.4.14-fpm-alpine

# Configure image maintainer
LABEL maintainer="Nicklas373 <herlambangdicky5@gmail.com>"
LABEL version="2.1"
LABEL description="Docker container for https://gw.hana-ci.com"

# Configure work directory
WORKDIR /var/www/html

# Configure timezone
ENV TZ="Asia/Jakarta"
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && \
    echo "Asia/Jakarta" > /etc/timezone

# Configure initial packages
RUN apk add --no-cache \
    curl \
    unzip \
    git \
    libzip-dev \
    freetype-dev \
    imagemagick-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    ghostscript \
    autoconf \
    build-base \
    postgresql-dev \
    libsodium-dev \
    supervisor \
    nginx \
    bash \
    busybox-suid \
    nano

# Install Imagick extension
RUN cd /tmp && curl -L -o /tmp/imagick.tar.gz https://pecl.php.net/get/imagick-3.8.0.tgz \
    && tar --strip-components=1 -xf /tmp/imagick.tar.gz \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && echo "extension=imagick.so" > /usr/local/etc/php/conf.d/ext-imagick.ini \
    && rm -rf /tmp/*

# Install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install -j$(nproc) gd zip pdo_pgsql ftp sodium

# Clone App Services
RUN git clone -b dev/be/master https://github.com/Nicklas373/Hana-PDF hanaci-api

# Configure Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN cd hanaci-api && composer install --no-interaction --no-scripts --no-progress --prefer-dist

# Configure App Service
COPY module/php/php.ini /usr/local/etc/php/conf.d/99-hana.ini
RUN cd hanaci-api && \
    mkdir -p hanaci-api/storage/app/public/batch && \
    mkdir -p hanaci-api/storage/app/public/download && \
    mkdir -p hanaci-api/storage/app/public/image && \
    mkdir -p hanaci-api/storage/app/public/pool && \
    mkdir -p hanaci-api/storage/app/public/upload
RUN cd hanaci-api && cp .env.example .env
RUN cd hanaci-api && \
    php artisan key:generate --no-interaction --quiet && \
    php artisan jwt:secret --no-interaction --quiet && \
    php artisan storage:link --no-interaction --quiet && \
    php artisan config:cache --quiet && \
    php artisan config:clear --quiet
RUN cd hanaci-api && chmod o+w /var/www/html/hanaci-api/storage/ -R
RUN cd hanaci-api && chmod o+w /var/www/html/hanaci-api/vendor/mpdf/mpdf/tmp/ -R

# Configure Laravel Env
RUN cd hanaci-api && echo "" >> .env
RUN cd hanaci-api && sed -i 's/APP_NAME=Laravel/APP_NAME="gw.hana-ci"/' .env
RUN cd hanaci-api && sed -i "s#APP_URL=http://localhost#APP_URL=http://sit.gw.hana-ci.com#" .env
RUN cd hanaci-api && sed -i "s/DB_CONNECTION=sqlite/DB_CONNECTION=pgsql/" .env
RUN cd hanaci-api && sed -i "s/# DB_HOST=127.0.0.1/DB_HOST=hana-db-services/" .env
RUN cd hanaci-api && sed -i "s/# DB_PORT=3306/DB_PORT=5432/" .env
RUN cd hanaci-api && sed -i "s/# DB_DATABASE=laravel/DB_DATABASE=postgres/" .env
RUN cd hanaci-api && sed -i "s/# DB_USERNAME=root/DB_USERNAME=$DB_USERNAME/" .env
RUN cd hanaci-api && sed -i "s/# DB_PASSWORD=/DB_PASSWORD=$DB_PASSWORD/" .env
RUN cd hanaci-api && echo "" >> .env
RUN cd hanaci-api && echo "ASPOSE_CLOUD_CLIENT_ID=xxxx" >> .env
RUN cd hanaci-api && echo "ASPOSE_CLOUD_TOKEN=xxxx" >> .env
RUN cd hanaci-api && echo "FTP_USERNAME=xxxx" >> .env
RUN cd hanaci-api && echo "FTP_USERPASS=xxxx" >> .env
RUN cd hanaci-api && echo "FTP_SERVER=xxxx" >> .env
RUN cd hanaci-api && echo "FTP_ROOT=xxxx" >> .env
RUN cd hanaci-api && echo "ILOVEPDF_PUBLIC_KEY=xxxx" >> .env
RUN cd hanaci-api && echo "ILOVEPDF_SECRET_KEY=xxxx" >> .env
RUN cd hanaci-api && echo "PDF_IMG_POOL=image" >> .env
RUN cd hanaci-api && echo "PDF_BATCH=batch" >> .env
RUN cd hanaci-api && echo "PDF_UPLOAD=upload" >> .env
RUN cd hanaci-api && echo "PDF_DOWNLOAD=download" >> .env
RUN cd hanaci-api && echo "PDF_POOL=pool" >> .env
RUN cd hanaci-api && echo "TELEGRAM_BOT_ID=xxxx" >> .env
RUN cd hanaci-api && echo "TELEGRAM_CHAT_ID=xxxx" >> .env
RUN cd hanaci-api && echo "HANA_UNIQUE_KEY=xxxx" >> .env
RUN cd hanaci-api && echo "MINIO_ACCESS_KEY=xxxx" >> .env
RUN cd hanaci-api && echo "MINIO_SECRET_KEY=xxxx" >> .env
RUN cd hanaci-api && echo "MINIO_REGION=us-east-1" >> .env
RUN cd hanaci-api && echo "MINIO_BUCKET=hana-pdf-sit" >> .env
RUN cd hanaci-api && echo "MINIO_ENDPOINT=xxxx" >> .env
RUN cd hanaci-api && echo "JWT_SECRET=xxx" >> .env
RUN cd hanaci-api && echo "JWT_ALGO=HS256" >> .env

# Configure permission
RUN cd hanaci-api && \
    chmod o+w /var/www/html/hanaci-api/storage/ -R && \
    chmod o+w /var/www/html/hanaci-api/vendor/mpdf/mpdf/tmp/ -R

# Configure Nginx Services
RUN mkdir /etc/nginx/sites-enabled
COPY module/nginx/nginx.conf /etc/nginx/nginx.conf
COPY module/nginx/sites-available/api-hanaci.conf /etc/nginx/sites-available/api-hanaci.conf
RUN ln -s /etc/nginx/sites-available/api-hanaci.conf /etc/nginx/sites-enabled/

# Set up cron job for Laravel scheduler
COPY module/hanaci/hanaci-api/api-cron /etc/crontabs/root
RUN touch /var/log/cron.log && chmod 0644 /var/log/cron.log

# Configure supervisord
COPY module/instance/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Expose necessary ports
EXPOSE 80 9000

# Start cron, Nginx, and PHP-FPM with supervisord
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
